export const data = [
    {
        id: "0",
        name: "Tierra",
        image: require("../assets/Earth.png"),
        imageBig: require("../assets/Earth-big.png"),
        style: "earthStyle",
        moons: "1",
        age: "4.5",
        temperatureHigh: "56 ",
        temperatureLow: "-89",
        description:
            'Tercer planeta del sistema solar a partir del Sol, el planeta Tierra es rocoso, con atmósfera gaseosa y temperatura media de 15°C. Tiene un satélite natural, la Luna, y la cantidad de agua existente en el planeta, también llamado "planeta azul", junto con la cantidad de oxígeno, permiten el desarrollo de la vida en el planeta, siendo el único conocido del sistema solar con vida humana.',
        link: "https://es.wikipedia.org/wiki/Tierra",
    },
    {
        id: "1",
        name: "Marte",
        image: require("../assets/Mars.png"),
        imageBig: require("../assets/Mars-big.png"),
        style: "marsStyle",
        moons: "2",
        age: "4.6",
        temperatureHigh: "20",
        temperatureLow: "-87",
        description:
            "Cuarto planeta a partir del Sol y el más visible desde la Tierra, Marte tiene dos satélites naturales “Fobos e Deimos”, siendo el segundo planeta más pequeño del sistema solar, después de Mercurio. También llamado “planeta rojo”, debido a las partículas de óxido de hierro presentes en su atmósfera, el planeta Marte es un planeta rocoso, frío y seco.",
        link: "https://es.wikipedia.org/wiki/Marte_(planeta)",
    },
    {
        id: "2",
        name: "Mercurio",
        image: require("../assets/Mercury.png"),
        imageBig: require("../assets/Mercury-big.png"),
        style: "mercuryStyle",
        moons: "0",
        age: "4.5",
        temperatureHigh: "350",
        temperatureLow: "-170",
        description:
            "Mercurio es el planeta más cercano al Sol. Es un planeta rocoso, desprovisto de satélites y atmósfera delgada, siendo además el planeta más pequeño del sistema solar. Por esta razón presenta temperaturas muy altas de aproximadamente 400°C. Por otro lado, la cara del planeta no iluminada por el sol puede alcanzar temperaturas de aproximadamente -170 °C. El movimiento de rotación del planeta es de 59 días, mientras que la revolución es de 87 días.",
        link: "https://es.wikipedia.org/wiki/Mercurio_(planeta)",
    },
    {
        id: "3",
        name: "Saturno",
        image: require("../assets/Saturn.png"),
        imageBig: require("../assets/Saturn-big.png"),
        style: "saturnStyle",
        moons: "82",
        age: "4.5",
        temperatureHigh: "−73",
        temperatureLow: "-191",
        description:
            "Segundo planeta más grande del sistema solar, después de Júpiter, Saturno es conocido por sus anillos, formados por roca, hielo y polvo. Sexto planeta desde el sol, después de Júpiter, Saturno es el planeta del sistema solar que tiene muchos satélites: 82 lunas.",
        link: "https://es.wikipedia.org/wiki/Saturno_(planeta)",
    },
    {
        id: "4",
        name: "Júpiter",
        image: require("../assets/Jupyter.png"),
        imageBig: require("../assets/Jupyter-big.png"),
        style: "jupyterStyle",
        moons: "79",
        age: "4.6",
        temperatureHigh: "-75",
        temperatureLow: "-163",
        description:
            "Júpiter es el planeta más grande del sistema solar. Es un planeta gaseoso (compuesto principalmente por hidrógeno), 1.300 veces más grande que el planeta Tierra. Quinto planeta desde el Sol, Júpiter tiene la mayor cantidad de satélites, 79 satélites, y tiene temperaturas de hasta -150°C",
        link: "https://es.wikipedia.org/wiki/Júpiter_(planeta)",
    },
    {
        id: "5",
        name: "Venus",
        image: require("../assets/Venus.png"),
        imageBig: require("../assets/Venus-big.png"),
        style: "venusStyle",
        moons: "14",
        age: "4.5",
        temperatureHigh: "499",
        temperatureLow: "-45",
        description:
            "Conocida como la “Estrella del Alba” por su fuerte brillo, Venus, al igual que Mercurio, es un planeta que no tiene satélite. Visible desde nuestro planeta, Venus es el segundo planeta desde el Sol y el más cercano al planeta Tierra. Es interesante notar que a pesar de que es el segundo planeta desde el Sol (después de Mercurio), Venus es el planeta más caliente del sistema solar, con temperaturas que pueden alcanzar los 480°C. Se asemeja al planeta Tierra en tamaño, composición, estructura, masa, densidad y fuerza gravitacional.",
        link: "https://es.wikipedia.org/wiki/Venus_(planeta)",
    },
    {
        id: "6",
        name: "Urano",
        image: require("../assets/Uranus.png"),
        imageBig: require("../assets/Uranus-big.png"),
        style: "uranusStyle",
        moons: "27",
        age: "4.6",
        temperatureHigh: "-185",
        temperatureLow: "-214",
        description:
            "Tercer planeta más grande del sistema solar y séptimo planeta desde el Sol, Urano es un planeta gaseoso que tiene una temperatura promedio de -185°C y tiene 27 satélites. Tiene una característica interesante en cuanto a su eje de rotación con casi noventa grados con relación al plano de su órbita, que a su vez es muy extensa.",
        link: "https://es.wikipedia.org/wiki/Urano_(planeta)",
    },
    {
        id: "7",
        name: "Neptuno",
        image: require("../assets/Neptune.png"),
        imageBig: require("../assets/Neptune-big.png"),
        style: "neptuneStyle",
        moons: "14",
        age: "4.5",
        temperatureHigh: "-217",
        temperatureLow: "-223",
        description:
            "Planeta del sistema solar más alejado del Sol y el cuarto en tamaño, Neptuno tiene 14 satélites naturales y tiene temperaturas medias de aproximadamente -200°C. Es un planeta gaseoso, compuesto principalmente de hidrógeno, helio, amoníaco, metano y agua. El movimiento de rotación del planeta dura unas 16 horas, mientras que su traducción es equivalente a 164 años terrestres.",
        link: "https://es.wikipedia.org/wiki/Neptuno_(planeta)",
    },
];
